import type { VocabEntry } from "../types";

const entries: VocabEntry[] = [
  {
    word: "ざるを得ない",
    reading: "ざるをえない",
    romaji: "zaru o enai",
    pos: "expression",
    en: "cannot help but; have no choice but to",
    zh: "不得不；只好",
  },
  {
    word: "せざるを得ない",
    reading: "せざるをえない",
    romaji: "sezaru o enai",
    pos: "expression",
    en: "cannot help but do; have no choice but to do",
    zh: "不得不做；只好做",
  },
  {
    word: "タバコ",
    reading: "タバコ",
    romaji: "tabako",
    pos: "noun",
    en: "tobacco; cigarette",
    zh: "香烟；烟草",
  },
  {
    word: "に際して",
    reading: "にさいして",
    romaji: "ni saishite",
    pos: "expression",
    en: "on the occasion of; at the time of",
    zh: "在……之际",
  },
  {
    word: "パスポート",
    reading: "パスポート",
    romaji: "pasupōto",
    pos: "noun",
    en: "passport",
    zh: "护照",
  },
  {
    word: "パン",
    reading: "パン",
    romaji: "pan",
    pos: "noun",
    en: "bread",
    zh: "面包",
  },
  {
    word: "また",
    reading: "また",
    romaji: "mata",
    pos: "adverb",
    en: "again; also",
    zh: "又；再；也",
  },
  {
    word: "まるで",
    reading: "まるで",
    romaji: "marude",
    pos: "adverb",
    en: "as if; just like",
    zh: "简直；好像",
  },
  {
    word: "悪い",
    reading: "わるい",
    romaji: "warui",
    pos: "i-adjective",
    en: "bad",
    zh: "坏的；不好的",
  },
  {
    word: "一時間",
    reading: "いちじかん",
    romaji: "ichijikan",
    pos: "noun",
    en: "one hour",
    zh: "一个小时",
  },
  {
    word: "運転",
    reading: "うんてん",
    romaji: "unten",
    pos: "noun",
    en: "driving; operation",
    zh: "驾驶；操作",
  },
  {
    word: "運動",
    reading: "うんどう",
    romaji: "undō",
    pos: "noun",
    en: "exercise; movement",
    zh: "运动",
  },
  {
    word: "音楽",
    reading: "おんがく",
    romaji: "ongaku",
    pos: "noun",
    en: "music",
    zh: "音乐",
  },
  {
    word: "下手",
    reading: "へた",
    romaji: "heta",
    pos: "na-adjective",
    en: "unskilled; poor at",
    zh: "笨拙；不擅长",
  },
  {
    word: "何も",
    reading: "なにも",
    romaji: "nani mo",
    pos: "expression",
    en: "(not) anything; nothing",
    zh: "什么都（不）",
  },
  {
    word: "恐れ",
    reading: "おそれ",
    romaji: "osore",
    pos: "noun",
    en: "fear; risk; possibility (of something bad)",
    zh: "恐惧；担忧；可能性",
  },
  {
    word: "靴",
    reading: "くつ",
    romaji: "kutsu",
    pos: "noun",
    en: "shoes",
    zh: "鞋子",
  },
  {
    word: "結婚",
    reading: "けっこん",
    romaji: "kekkon",
    pos: "noun",
    en: "marriage",
    zh: "结婚",
  },
  {
    word: "嫌い",
    reading: "きらい",
    romaji: "kirai",
    pos: "na-adjective",
    en: "disliked; hateful",
    zh: "讨厌；厌恶",
  },
  {
    word: "限り",
    reading: "かぎり",
    romaji: "kagiri",
    pos: "noun",
    en: "as long as; limit; extent",
    zh: "只要；限度；范围",
  },
  {
    word: "高くて",
    reading: "たかくて",
    romaji: "takakute",
    pos: "expression",
    en: "being expensive/tall (and)",
    zh: "又贵又……；又高又……",
  },
  {
    word: "今すぐ",
    reading: "いますぐ",
    romaji: "ima sugu",
    pos: "adverb",
    en: "right now; immediately",
    zh: "马上；立刻",
  },
  {
    word: "桜",
    reading: "さくら",
    romaji: "sakura",
    pos: "noun",
    en: "cherry blossom",
    zh: "樱花",
  },
  {
    word: "残業",
    reading: "ざんぎょう",
    romaji: "zangyō",
    pos: "noun",
    en: "overtime work",
    zh: "加班",
  },
  {
    word: "思う",
    reading: "おもう",
    romaji: "omou",
    pos: "verb-godan",
    en: "to think; to feel",
    zh: "想；觉得",
  },
];

export default entries;
